"""Added Field fd_team_id in Teams

Revision ID: 01f4140369c0
Revises: b6f7f158d6a3
Create Date: 2025-07-12 19:24:20.677864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f4140369c0'
down_revision = 'b6f7f158d6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fd_team_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('fd_team_id')

    # ### end Alembic commands ###
