"""Rename field country to stadium

Revision ID: 49fb74384612
Revises: cd5e15de251e
Create Date: 2025-07-12 15:43:38.916862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fb74384612'
down_revision = 'cd5e15de251e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stadium', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('favourite', sa.Boolean(), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('favourite')
        batch_op.drop_column('stadium')

    # ### end Alembic commands ###
