"""Added Field fd_competition in League

Revision ID: b338b903f763
Revises: 01f4140369c0
Create Date: 2025-07-12 19:53:07.810764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b338b903f763'
down_revision = '01f4140369c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fd_competition', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('fd_competition')

    # ### end Alembic commands ###
